name: Generate Installable Theme and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/wp-content/themes/twentyseventeen
          repository: 'ClassicPress/ClassicPress'
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create artifact and bring last commit
        id: last-commit
        run : |
          cd src/wp-content/themes/
          ( echo "LAST_UPSTREAM_COMMIT="; git log -1 -- twentyseventeen | grep -E '\(\#[0-9]+\)' ) >> $GITHUB_OUTPUT
          zip -r twentyseventeen.zip twentyseventeen 
          ls
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twentyseventeen
          path: src/wp-content/themes/twentyseventeen.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: src/wp-content/themes/twentyseventeen.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: djn24/add-comment-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          comment: |-
            Last commit:
            ${{ steps.last-commit.outputs.LAST_UPSTREAM_COMMIT }}
